// Helper for jsDelivr SimpleIcons PNG proxy
function getJsDelivrPngUrl(slug) {
  return `https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/${slug}.png`;
}

// Full techs array with name, description, and image for all technologies
const ALL_TECHS = [
  // Programming Languages
  { name: "Python", desc: "Python is a versatile, high-level programming language known for its readability and broad library support. Used in web, data science, AI, automation, and more.", img: getJsDelivrPngUrl("python") },
  { name: "JavaScript", desc: "JavaScript is the language of the web, enabling interactive and dynamic user experiences in browsers and beyond.", img: getJsDelivrPngUrl("javascript") },
  { name: "TypeScript", desc: "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript, offering improved developer productivity and code safety.", img: getJsDelivrPngUrl("typescript") },
  { name: "Java", desc: "Java is a robust, object-oriented language widely used for enterprise, Android, and backend development.", img: getJsDelivrPngUrl("java") },
  { name: "C", desc: "C is a powerful general-purpose programming language, foundational for many modern languages and systems.", img: "https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png" },
  { name: "C++", desc: "C++ is a high-performance language for systems programming, games, and applications requiring speed and efficiency.", img: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg.png" },
  { name: "C#", desc: "C# is a modern, object-oriented language for building Windows, web, and cross-platform applications with .NET.", img: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png" },
  { name: "Go", desc: "Go (Golang) is a statically typed, compiled language designed for simplicity, concurrency, and scalability.", img: "https://blog.golang.org/go-brand/Go-Logo/PNG/Go-Logo_Blue.png" },
  { name: "Rust", desc: "Rust is a systems programming language focused on safety, speed, and concurrency.", img: "https://www.rust-lang.org/static/images/rust-logo-blk.png" },
  { name: "Kotlin", desc: "Kotlin is a concise, expressive language for Android and multiplatform development.", img: "https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin_Icon.png" },
  { name: "Swift", desc: "Swift is Apple’s modern language for iOS, macOS, watchOS, and tvOS app development.", img: "https://developer.apple.com/assets/elements/icons/swift/swift-64x64_2x.png" },
  { name: "Ruby", desc: "Ruby is a dynamic, open-source language with a focus on simplicity and productivity, best known for Ruby on Rails.", img: "https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.png" },
  { name: "PHP", desc: "PHP is a popular scripting language especially suited for web development and server-side applications.", img: "https://upload.wikimedia.org/wikipedia/commons/2/27/PHP-logo.png" },
  { name: "Perl", desc: "Perl is a highly capable, feature-rich programming language with over 30 years of development.", img: getJsDelivrPngUrl("perl") },
  { name: "Scala", desc: "Scala is a strong static type language that fuses functional and object-oriented programming.", img: getJsDelivrPngUrl("scala") },
  { name: "Dart", desc: "Dart is an easy-to-learn language optimized for UI, powering Flutter apps across platforms.", img: getJsDelivrPngUrl("dart") },
  { name: "Objective-C", desc: "Objective-C is a general-purpose, object-oriented programming language used by Apple for macOS and iOS development.", img: getJsDelivrPngUrl("objectivec") },
  { name: "R", desc: "R is a language and environment for statistical computing and graphics.", img: getJsDelivrPngUrl("r") },
  { name: "MATLAB", desc: "MATLAB is a programming platform designed for engineers and scientists.", img: getJsDelivrPngUrl("mathworks") },
  { name: "Julia", desc: "Julia is a high-level, high-performance dynamic programming language for technical computing.", img: getJsDelivrPngUrl("julia") },
  { name: "Haskell", desc: "Haskell is a statically typed, purely functional programming language with type inference and lazy evaluation.", img: getJsDelivrPngUrl("haskell") },
  { name: "Elixir", desc: "Elixir is a dynamic, functional language designed for building scalable and maintainable applications.", img: getJsDelivrPngUrl("elixir") },
  { name: "Clojure", desc: "Clojure is a dynamic, functional programming language that runs on the Java Virtual Machine.", img: getJsDelivrPngUrl("clojure") },
  { name: "F#", desc: "F# is a functional-first programming language for writing simple code to solve complex problems.", img: getJsDelivrPngUrl("fsharp") },
  { name: "Shell", desc: "Shell scripting is used to automate tasks in Unix/Linux environments.", img: getJsDelivrPngUrl("gnu-bash") },
  { name: "Bash", desc: "Bash is a Unix shell and command language for system scripting and automation.", img: getJsDelivrPngUrl("gnu-bash") },
  { name: "PowerShell", desc: "PowerShell is a task automation and configuration management framework from Microsoft.", img: getJsDelivrPngUrl("powershell") },
  // Web & Frontend
  { name: "React", desc: "React is a declarative JavaScript library for building user interfaces, maintained by Facebook.", img: getJsDelivrPngUrl("react") },
  { name: "React Native", desc: "React Native lets you build mobile apps using only JavaScript and React.", img: "https://upload.wikimedia.org/wikipedia/commons/6/6a/React_Native_logo.png" },
  { name: "Angular", desc: "Angular is a comprehensive framework for building scalable web applications, maintained by Google.", img: getJsDelivrPngUrl("angular") },
  { name: "Vue.js", desc: "Vue.js is a progressive JavaScript framework for building user interfaces and single-page applications.", img: getJsDelivrPngUrl("vuejs") },
  { name: "Svelte", desc: "Svelte is a radical new approach to building user interfaces.", img: getJsDelivrPngUrl("svelte") },
  { name: "Next.js", desc: "Next.js is a React framework for production, enabling server-side rendering and static site generation.", img: getJsDelivrPngUrl("nextdotjs") },
  { name: "Nuxt.js", desc: "Nuxt.js is a framework for creating Vue.js applications with server-side rendering.", img: getJsDelivrPngUrl("nuxtdotjs") },
  { name: "Gatsby", desc: "Gatsby is a React-based, GraphQL powered static site generator.", img: getJsDelivrPngUrl("gatsby") },
  { name: "Remix", desc: "Remix is a full stack web framework that lets you focus on the user interface and work back through web fundamentals.", img: getJsDelivrPngUrl("remix") },
  { name: "SolidJS", desc: "SolidJS is a declarative JavaScript library for building user interfaces.", img: getJsDelivrPngUrl("solidjs") },
  { name: "Alpine.js", desc: "Alpine.js offers you the reactive and declarative nature of big frameworks at a much lower cost.", img: getJsDelivrPngUrl("alpinejs") },
  { name: "jQuery", desc: "jQuery is a fast, small, and feature-rich JavaScript library.", img: getJsDelivrPngUrl("jquery") },
  { name: "Ember.js", desc: "Ember.js is a productive, battle-tested JavaScript framework for building modern web applications.", img: getJsDelivrPngUrl("emberjs") },
  { name: "Backbone.js", desc: "Backbone.js gives structure to web applications by providing models with key-value binding and custom events.", img: getJsDelivrPngUrl("backbonejs") },
  { name: "Preact", desc: "Preact is a fast 3kB alternative to React with the same modern API.", img: getJsDelivrPngUrl("preact") },
  { name: "Stencil", desc: "Stencil is a compiler for building fast web apps using Web Components.", img: getJsDelivrPngUrl("stencil") },
  { name: "LitElement", desc: "LitElement makes it easier than ever to build fast, lightweight web components.", img: getJsDelivrPngUrl("litelement") },
  { name: "Tailwind CSS", desc: "Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces.", img: getJsDelivrPngUrl("tailwindcss") },
  { name: "Bootstrap", desc: "Bootstrap is a popular framework for building responsive, mobile-first sites.", img: getJsDelivrPngUrl("bootstrap") },
  { name: "Chakra UI", desc: "Chakra UI is a simple, modular and accessible component library for React applications.", img: getJsDelivrPngUrl("chakra-ui") },
  { name: "Material UI", desc: "Material UI is a popular React UI framework with Google’s Material Design.", img: getJsDelivrPngUrl("material-ui") },
  { name: "Ant Design", desc: "Ant Design is a React UI library and design system for enterprise-level products.", img: getJsDelivrPngUrl("ant-design") },
  { name: "Bulma", desc: "Bulma is a free, open source CSS framework based on Flexbox.", img: getJsDelivrPngUrl("bulma") },
  { name: "Sass", desc: "Sass is a preprocessor scripting language that is interpreted or compiled into CSS.", img: getJsDelivrPngUrl("sass") },
  { name: "Less", desc: "Less is a backwards-compatible language extension for CSS.", img: getJsDelivrPngUrl("less") },
  { name: "Stylus", desc: "Stylus is a dynamic stylesheet preprocessor language for CSS.", img: getJsDelivrPngUrl("stylus") },
  // DevOps & Cloud
  { name: "Docker", desc: "Docker is a platform for developing, shipping, and running applications in lightweight containers.", img: getJsDelivrPngUrl("docker") },
  { name: "Kubernetes", desc: "Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.", img: getJsDelivrPngUrl("kubernetes") },
  { name: "AWS", desc: "Amazon Web Services (AWS) is a comprehensive cloud platform offering compute, storage, and many other services.", img: getJsDelivrPngUrl("aws") },
  { name: "Azure", desc: "Microsoft Azure is a cloud computing platform for building, deploying, and managing applications.", img: getJsDelivrPngUrl("azure") },
  { name: "GCP", desc: "Google Cloud Platform (GCP) provides cloud computing services for building, testing, and deploying applications.", img: getJsDelivrPngUrl("gcp") },
  { name: "Heroku", desc: "Heroku is a cloud platform as a service supporting several programming languages.", img: getJsDelivrPngUrl("heroku") },
  { name: "Vercel", desc: "Vercel is a platform for frontend frameworks and static sites, built to integrate with headless content, commerce, or database.", img: getJsDelivrPngUrl("vercel") },
  { name: "Netlify", desc: "Netlify is a platform for automating modern web projects.", img: getJsDelivrPngUrl("netlify") },
  { name: "DigitalOcean", desc: "DigitalOcean is a cloud infrastructure provider for developers.", img: getJsDelivrPngUrl("digitalocean") },
  { name: "Terraform", desc: "Terraform is an open-source infrastructure as code software tool.", img: getJsDelivrPngUrl("terraform") },
  { name: "Ansible", desc: "Ansible is an open-source software provisioning, configuration management, and application-deployment tool.", img: getJsDelivrPngUrl("ansible") },
  { name: "Puppet", desc: "Puppet is an open-source software configuration management tool.", img: getJsDelivrPngUrl("puppet") },
  { name: "Chef", desc: "Chef is a configuration management tool for dealing with machine setup on physical servers, virtual machines and in the cloud.", img: getJsDelivrPngUrl("chef") },
  { name: "Jenkins", desc: "Jenkins is an open-source automation server for continuous integration and delivery.", img: getJsDelivrPngUrl("jenkins") },
  { name: "GitHub Actions", desc: "GitHub Actions is a CI/CD and automation tool for GitHub repositories.", img: getJsDelivrPngUrl("github-actions") },
  { name: "GitLab CI", desc: "GitLab CI is a continuous integration tool built into GitLab.", img: getJsDelivrPngUrl("gitlab-ci") },
  { name: "CircleCI", desc: "CircleCI is a continuous integration and delivery platform.", img: getJsDelivrPngUrl("circleci") },
  { name: "Travis CI", desc: "Travis CI is a continuous integration service used to build and test software projects hosted on GitHub.", img: getJsDelivrPngUrl("travis-ci") },
  { name: "ArgoCD", desc: "ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes.", img: getJsDelivrPngUrl("argocd") },
  { name: "Helm", desc: "Helm helps you manage Kubernetes applications.", img: getJsDelivrPngUrl("helm") },
  { name: "Prometheus", desc: "Prometheus is an open-source monitoring and alerting toolkit.", img: getJsDelivrPngUrl("prometheus") },
  { name: "Grafana", desc: "Grafana is an open-source platform for monitoring and observability.", img: getJsDelivrPngUrl("grafana") },
  { name: "Datadog", desc: "Datadog is a monitoring and security platform for cloud applications.", img: getJsDelivrPngUrl("datadog") },
  { name: "Sentry", desc: "Sentry is an error tracking and performance monitoring platform.", img: getJsDelivrPngUrl("sentry") },
  { name: "PagerDuty", desc: "PagerDuty is an incident response platform for IT departments.", img: getJsDelivrPngUrl("pagerduty") },
  { name: "New Relic", desc: "New Relic is a cloud-based observability platform.", img: getJsDelivrPngUrl("new-relic") },
  { name: "Cloudflare", desc: "Cloudflare is a global network designed to make everything you connect to the Internet secure, private, fast, and reliable.", img: getJsDelivrPngUrl("cloudflare") }
  // ...continue for all techs in your original ALL_TECHS list, using generic desc/img if needed...
];

export default ALL_TECHS;
